services:
  postgres:
    image: postgres:16
    container_name: tagespostgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    volumes:
      - ./localfs.data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 3s
      timeout: 30s
      retries: 10

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheusTages
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - postgres
